apiVersion: apps/v1                # Especifica a versão da API para o Deployment (apps/v1 é o mais recente para Deployments)
kind: Deployment                   # Tipo de recurso que está sendo criado (Deployment)
metadata:
  name: tech-challenge02-app            # Nome do Deployment
spec:
  replicas: 2                      # Define o número de réplicas (instâncias) do pod
  selector:
    matchLabels:
      app: tech-challenge02-app         # Seleciona os pods que possuem este label para fazer parte do Deployment
  template:
    metadata:
      labels:
        app: tech-challenge02-app       # Label que será usado para identificar os pods criados por este template
    spec:
      containers:
        - name: tech-challenge02-app      # Nome do contêiner dentro do pod
          image: irlan/tech-challenge-02:latest   # Imagem Docker do contêiner, substitua pela sua imagem
          ports:
            - containerPort: 8080      # Porta no contêiner que será exposta
          envFrom:
            - configMapRef:
                name: app-config       # Referência a um ConfigMap chamado "app-config" para variáveis de ambiente
          env:
            - name: SPRING_DATASOURCE_URL     # Variável de ambiente específica
              value: jdbc:mysql://mysql-db:3306/lanchonete?useTimezone=true&serverTimezone=America/Sao_Paulo
