apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  replicas: 2  # Quantidade de réplicas da aplicação
  selector:
    matchLabels:
      app: backend-app  # Seleciona pods com essa label
  template:
    metadata:
      labels:
        app: backend-app  # Associa esse label ao pod criado
    spec:
      # initContainers:
      # - name: migration
      #   image: irlan/clean-architecture-nestjs-backend  # Sua imagem
      #   command: ["npm", "run", "migration:run"]  # Comando para rodar a migração
      #   envFrom:
      #   - configMapRef:
      #       name: app-config
      #   env:
      #   - name: DB_HOST
      #     value: postgres-db-service # Substitua pelo nome do seu service
      #   - name: DB_PORT
      #     value: "5432"
      #   - name: DB_USERNAME
      #     value: root
      #   - name: DB_PASSWORD
      #     value: root
      #   - name: DB_NAME
      #     value: lanchonete    
      containers:
      - name: backend-app
        image: irlan/clean-architecture-nestjs-backend:1.0.0  # Imagem do Node.js 
        ports:
        - containerPort: 3000  # Porta exposta pela aplicação
        resources:
          requests:   # Recursos mínimos para cada pod
            memory: "512Mi"
            cpu: "500m"
          limits:     # Limites máximos para cada pod
            memory: "1024Mi"
            cpu: "1"        
        env:
        - name: SERVER_PORT
          value: "3000"  # Porta do servidor
        - name: DB_HOST
          value: postgres-db  # O serviço do banco de dados no cluster
        - name: DB_PORT
          value: "5432"
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username  # Referência a um Secret com as credenciais do banco
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: DB_NAME
          value: postgres
        - name: DB_ADMIN_EMAIL
          value: admin@root.com
        - name: NODE_ENV
          value: production
