apiVersion: v1
kind: Service
metadata:
  name: postgres-db
spec:
  selector:
    app: postgres-db  # Conecta-se ao pod do PostgreSQL
  ports:
    - protocol: TCP
      port: 5432  # Porta do serviço no cluster
      targetPort: 5432  # Porta do container
  type: ClusterIP  # Disponível apenas dentro do cluster
