apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce  # Volume pode ser montado apenas por um nรณ
  resources:
    requests:
      storage: 1Gi  # 1 GB de armazenamento solicitado
